#!/bin/bash

clone_repo(){
    local repo="$1"
    local name="${repo#*/}"
    echo "checking $name ..."
    if ! [[ -e $name ]]; then
        git clone "https://github.com/$repo"
    else
        echo "$name already exists"
    fi
    echo
}

git_repos=(
    'taocpp/PEGTL'
)

cd src || exit 1
for repo in "${git_repos[@]}"; do
    clone_repo "$repo"
done

( cd PEGTL && git checkout be1d0b459f790f4bd14814499c458d4abd3a64b6 )
